apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-v2
  labels:
    app: service2
spec:
  selector:
    matchLabels:
      app: service2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service2
        version: v2
    spec:
      containers:
      - image: zoliczako/sssm-service2:1.0.0
        imagePullPolicy: Always
        name: service2
        ports:
          - containerPort: 5002
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"