apiVersion: apps/v1
kind: Deployment
metadata:
  name: service5
  labels:
    app: service5
spec:
  selector:
    matchLabels:
      app: service5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service5
        version: v1
    spec:
      containers:
      - image: zoliczako/sssm-service5:1.0.0
        imagePullPolicy: Always
        name: service5
        ports:
          - containerPort: 5005
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service5
  labels:
    app: service5
spec:
  ports:
  - name: http
    port: 5005
    targetPort: 5005
  selector:
    app: service5