apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  labels:
    app: service3
spec:
  selector:
    matchLabels:
      app: service3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service3
        version: v1
    spec:
      containers:
      - image: zoliczako/sssm-service3:1.0.0
        imagePullPolicy: Always
        name: service3
        ports:
          - containerPort: 5003
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: service3
  labels:
    app: service3
spec:
  ports:
  - name: http
    port: 5003
    targetPort: 5003
  selector:
    app: service3